'use strict';
const $=s=>document.querySelector(s);
const icons=()=>window.lucide?.createIcons();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<i data-lucide="${n}"></i>`;
const button=(action,id,title,symbol,extra='')=>`<button class="icon-button ${extra}" data-action="${action}" data-id="${esc(id)}" title="${title}" aria-label="${title}">${icon(symbol)}</button>`;
let state={databases:[],strategies:[],executions:[],diagnostics:{},active:{},nextRuns:{}};
let currentView='strategies',formTimes=[],detail={id:null,script:'',log:'',mode:'script'},refreshing=false;
const methods={FULL:'Completo',LEVEL0:'Incremental nivel 0',LEVEL1:'Nivel 1 diferencial',CUMULATIVE:'Nivel 1 acumulativo'};
const formatDate=value=>value?new Intl.DateTimeFormat('es-CR',{timeZone:'America/Guatemala',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)):'Sin programar';
const dbName=id=>state.databases.find(d=>d.id===id)?.name||'Base eliminada';
function badge(status){const style={CORRECTA:'good',FALLIDA:'bad',EJECUTANDO:'blue',INCIERTO:'warn',OMITIDA:'warn',Programada:'good',Pausada:''}[status]||'';return `<span class="badge ${style}">${esc(status)}</span>`;}
function toast(message,error=false){const t=$('#toast');t.textContent=message;t.className='toast'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),6500);}
async function api(path,body){const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data;try{data=await r.json();}catch{throw Error('El servidor no responde.');}if(!r.ok)throw Error(data.error||'No se pudo completar la operacion.');return data;}
async function refresh(){if(refreshing)return;refreshing=true;try{state=await api('state');render();$('#connection-text').textContent='Servidor conectado';$('#connection-dot').className='dot ok';if($('#detail-dialog').open&&detail.id)await updateDetail();}catch(e){$('#connection-text').textContent='Sin conexion';$('#connection-dot').className='dot bad';}finally{refreshing=false;}}
function switchView(view){currentView=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==view+'-view'));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#view-title').textContent={strategies:'Estrategias de respaldo',executions:'Ejecuciones',databases:'Bases de datos'}[view];$('#new-button').classList.toggle('hidden',view==='executions');$('#new-button').innerHTML=icon('plus')+(view==='databases'?'Registrar base':'Nueva estrategia');icons();}
function render(){
  $('#metric-strategies').textContent=state.strategies.length;$('#metric-scheduled').textContent=state.strategies.filter(s=>s.enabled).length;$('#metric-bases').textContent=state.databases.length+' bases registradas';
  const last=state.executions.find(e=>e.status==='CORRECTA'&&e.operation==='BACKUP');$('#metric-last').textContent=last?formatDate(last.finishedAt):'Sin ejecuciones';$('#metric-last-name').textContent=last?.strategyName||'Ningun respaldo registrado';$('#metric-failed').textContent=state.executions.filter(e=>e.status==='FALLIDA').length;
  const selection=$('#database-filter').value;$('#database-filter').innerHTML='<option value="">Todas las bases</option>'+state.databases.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('');$('#database-filter').value=selection;
  renderStrategies();renderExecutions();renderDatabases();$('#updated-at').textContent='Actualizado '+formatDate(state.serverTime);icons();
}
function renderStrategies(){const term=$('#search').value.toLowerCase(),filter=$('#status-filter').value,db=$('#database-filter').value;const rows=state.strategies.filter(s=>(!db||s.databaseId===db)&&(!term||(s.name+' '+dbName(s.databaseId)).toLowerCase().includes(term))&&(!filter||s.enabled===(filter==='active')));
  $('#strategy-count').textContent=rows.length+' registradas';$('#strategy-foot').textContent=rows.length+' de '+state.strategies.length+' estrategias';
  $('#strategies-body').innerHTML=rows.length?rows.map(s=>`<tr><td><strong>${esc(s.name)}</strong><small>${esc(dbName(s.databaseId))} &middot; Prioridad ${esc(s.priority.toLowerCase())}</small></td><td><strong>${s.scope==='DATABASE'?'Base completa':esc(s.tablespaces.join(', '))}</strong><small>${methods[s.method]}${s.archivelogs?' + logs':''}${s.controlfile?' + control':''}</small></td><td class="times-cell">${s.times.length?esc(s.times.join(' · ')):'Sin horarios'}</td><td><small>${formatDate(state.nextRuns[s.id])}</small></td><td>${state.active[s.databaseId]?badge('EJECUTANDO'):badge(s.enabled?'Programada':'Pausada')}</td><td><div class="row-actions">${button('run',s.id,'Ejecutar respaldo','play','run')}${button('validate',s.id,'Verificar respaldo','shield-check')}${button('preview',s.id,'Ver script RMAN','file-code-2')}${button('edit',s.id,'Editar estrategia','pencil')}${button('delete',s.id,'Eliminar estrategia','trash-2')}</div></td></tr>`).join(''):`<tr><td colspan="6" class="empty">${icon('layers')}No hay estrategias para esta seleccion.</td></tr>`;icons();}
function duration(e){if(!e.finishedAt)return 'En curso';const seconds=Math.max(0,Math.round((Date.parse(e.finishedAt)-Date.parse(e.startedAt))/1000));return seconds<60?seconds+' s':Math.floor(seconds/60)+' min '+seconds%60+' s';}
function renderExecutions(){const filter=$('#execution-filter').value,rows=state.executions.filter(e=>!filter||e.status===filter);$('#executions-body').innerHTML=rows.length?rows.map(e=>`<tr><td>${formatDate(e.startedAt)}</td><td><strong>${esc(e.strategyName)}</strong><small>${esc(dbName(e.databaseId))}</small></td><td>${e.operation==='BACKUP'?'Respaldo':'Validacion'}</td><td>${e.source==='HORARIO'?'Programada':'Manual'}</td><td>${duration(e)}</td><td>${badge(e.status)}</td><td>${button('detail',e.id,'Abrir registro','file-text')}</td></tr>`).join(''):`<tr><td colspan="7" class="empty">${icon('history')}Todavia no hay ejecuciones${filter?' con este resultado':''}.</td></tr>`;icons();}
function renderDatabases(){$('#databases-list').innerHTML=state.databases.map(d=>{const report=state.diagnostics[d.id];return `<article class="database-item"><div class="database-head">${icon('database')}<div><strong>${esc(d.name)}</strong><small>${esc(d.container)}</small></div></div>${badge(report?report.ready?'CORRECTA':'INCIERTO':'Sin comprobar')}<div class="database-info">${report?esc(report.output.trim()):'Diagnostico pendiente'}</div><button class="secondary" data-action="diagnose" data-id="${d.id}">${icon('plug-zap')}Comprobar conexion</button></article>`;}).join('');}
const form=$('#strategy-form');const field=name=>form.elements.namedItem(name);
function openStrategy(s){form.reset();field('id').value=s?.id||'';field('name').value=s?.name||'';field('databaseId').innerHTML=state.databases.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('');if(s)field('databaseId').value=s.databaseId;field('scope').value=s?.scope||'TABLESPACE';field('tablespaces').value=s?.tablespaces.join(', ')||'FREEPDB1:LAB_DATOS';field('method').value=s?.method||'FULL';field('priority').value=s?.priority||'ALTA';field('archivelogs').checked=s?.archivelogs??true;field('controlfile').checked=s?.controlfile??true;field('enabled').checked=s?.enabled??false;formTimes=[...(s?.times||[])];$('#form-error').textContent='';$('#strategy-dialog-title').textContent=s?'Editar estrategia':'Nueva estrategia';renderTimes();scopeChanged();$('#strategy-dialog').showModal();}
function readStrategy(){return {id:field('id').value||null,name:field('name').value,databaseId:field('databaseId').value,scope:field('scope').value,tablespaces:field('scope').value==='TABLESPACE'?field('tablespaces').value.split(/[,\s]+/).filter(Boolean):[],method:field('method').value,priority:field('priority').value,archivelogs:field('archivelogs').checked,controlfile:field('controlfile').checked,times:formTimes,enabled:field('enabled').checked};}
function scopeChanged(){$('#tablespaces-field').classList.toggle('hidden',field('scope').value==='DATABASE');}
function renderTimes(){$('#times-list').innerHTML=formTimes.map(t=>`<span class="time-chip">${esc(t)}<button type="button" data-remove-time="${esc(t)}" aria-label="Quitar horario ${esc(t)}">${icon('x')}</button></span>`).join('');icons();}
function openDetail(title,script,log='',id=null,message=''){detail={id,script,log,mode:id?'log':'script'};$('#detail-title').textContent=title;$('#detail-message').textContent=message;$('#detail-eyebrow').textContent=id?'EJECUCION':'RMAN';$('#show-log').classList.toggle('hidden',!id);showDetail();if(!$('#detail-dialog').open)$('#detail-dialog').showModal();}
function showDetail(){$('#detail-content').textContent=detail[detail.mode]||'Esperando salida de RMAN...';$('#show-log').classList.toggle('selected',detail.mode==='log');$('#show-script').classList.toggle('selected',detail.mode==='script');}
async function updateDetail(){const value=await api('executions/'+detail.id);detail.script=value.script;detail.log=value.log;$('#detail-message').textContent=value.execution.status+' · '+value.execution.message;showDetail();}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>switchView(n.dataset.view)));
document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$('#new-button').addEventListener('click',()=>{if(currentView==='databases'){$('#database-form').reset();$('#db-error').textContent='';$('#database-dialog').showModal();}else openStrategy();});
$('#refresh').addEventListener('click',refresh);$('#search').addEventListener('input',renderStrategies);$('#database-filter').addEventListener('change',renderStrategies);$('#status-filter').addEventListener('change',renderStrategies);$('#execution-filter').addEventListener('change',renderExecutions);
document.querySelectorAll('input[name=scope]').forEach(el=>el.addEventListener('change',scopeChanged));
$('#add-time').addEventListener('click',()=>{const value=$('#time-input').value;if(!value)return;if(!formTimes.includes(value))formTimes.push(value);formTimes.sort();renderTimes();});
$('#times-list').addEventListener('click',e=>{const button=e.target.closest('[data-remove-time]');if(button){formTimes=formTimes.filter(t=>t!==button.dataset.removeTime);renderTimes();}});
form.addEventListener('submit',async e=>{e.preventDefault();const submit=form.querySelector('[type=submit]');submit.disabled=true;try{await api('strategies',readStrategy());$('#strategy-dialog').close();toast('Estrategia guardada.');await refresh();}catch(error){$('#form-error').textContent=error.message;}finally{submit.disabled=false;}});
$('#database-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const b=f.querySelector('[type=submit]');b.disabled=true;try{await api('databases',{name:f.elements.name.value,container:f.elements.container.value});$('#database-dialog').close();toast('Base registrada.');await refresh();}catch(error){$('#db-error').textContent=error.message;}finally{b.disabled=false;}});
$('#preview-form').addEventListener('click',async()=>{try{const result=await api('preview',{strategy:readStrategy()});openDetail('Script de la estrategia',result.script);}catch(error){$('#form-error').textContent=error.message;}});
document.body.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,id}=b.dataset;b.disabled=true;try{
  const s=state.strategies.find(s=>s.id===id);
  if(action==='edit')openStrategy(s);
  if(action==='preview'){const result=await api('preview',{strategy:s});openDetail(s.name,result.script);}
  if(action==='delete'&&confirm('Eliminar la estrategia "'+s.name+'"? El historial se conserva.')){await api('strategies/delete',{id});toast('Estrategia eliminada.');await refresh();}
  if(action==='run'||action==='validate'){const result=await api('run',{strategyId:id,operation:action==='run'?'BACKUP':'VALIDATE'});switchView('executions');await refresh();const data=await api('executions/'+result.id);openDetail(data.execution.strategyName,data.script,data.log,result.id,data.execution.message);toast(action==='run'?'Respaldo iniciado.':'Validacion iniciada.');}
  if(action==='detail'){const data=await api('executions/'+id);openDetail(data.execution.strategyName,data.script,data.log,id,data.execution.status+' · '+data.execution.message);}
  if(action==='diagnose'){b.innerHTML=icon('loader-circle')+'Comprobando...';icons();const result=await api('diagnose',{databaseId:id});toast(result.message,!result.ready);await refresh();}
}catch(error){toast(error.message,true);}finally{b.disabled=false;}});
$('#show-log').addEventListener('click',()=>{detail.mode='log';showDetail();});$('#show-script').addEventListener('click',()=>{detail.mode='script';showDetail();});
$('#download-detail').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([detail[detail.mode]],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=detail.mode==='script'?'estrategia.rman':'ejecucion.log';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
icons();refresh();setInterval(refresh,3000);
